version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.2
    environment:
      POSTGRES_DB: "task_management_system"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_management_system"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "secret"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pg_admin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

  core:
    container_name: task-management-core
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - task-management-system-mvn:/root/.m2
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/task_management_system
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    networks:
      - postgres

  ui:
    container_name: task-management-ui
    build: "./ui"
    ports:
      - "80:80"
    volumes:
      - task-management-system-npm:/app/node_modules
    depends_on:
      - core

networks:
  postgres:
    driver: bridge

volumes:
  pg_data:
  pg_admin:
  task-management-system-mvn:
  task-management-system-npm:

