CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    ID SERIAL PRIMARY KEY,
    ROLE VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITY_USER
(
    AUTHORITY_ID BIGINT NOT NULL,
    USER_ID      BIGINT NOT NULL,
    FOREIGN KEY (AUTHORITY_ID)
        REFERENCES AUTHORITIES (ID)
        ON DELETE CASCADE,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
        ON DELETE CASCADE,
    UNIQUE (AUTHORITY_ID, USER_ID)
);