spring:
  application:
    name: core

  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_system
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true

  flyway:
    locations: classpath:db/migration/prod
